# Generated by Django 2.1.11 on 2019-11-30 15:18

import core.validater
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.ImageField(blank=True, default='head_photo/default.jpg', max_length=500, null=True, upload_to='head_photo/', validators=[core.validater.validate_image], verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=64, null=True, verbose_name='昵称'),
        ),
    ]
