# Generated by Django 2.1.1 on 2019-11-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='type',
            field=models.IntegerField(blank=True, choices=[(0, '离职'), (1, '工人'), (2, '大组长'), (3, '经理'), (4, '总经理')], null=True, verbose_name='员工类别'),
        ),
    ]
