# Generated by Django 2.2.7 on 2019-11-16 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191116_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='head_photo/', verbose_name='头像'),
        ),
    ]
