# Generated by Django 2.2.7 on 2019-11-16 16:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamstatmember',
            options={'verbose_name': '小组工人排班表', 'verbose_name_plural': '小组工人排班表'},
        ),
        migrations.AlterField(
            model_name='group',
            name='employee',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='employee_group', to='sms.Member', verbose_name='大组管理员工号'),
        ),
        migrations.AlterField(
            model_name='group',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='大组号'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=255, verbose_name='大组名'),
        ),
        migrations.AlterField(
            model_name='member',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='member',
            name='birthplace',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='所在地'),
        ),
        migrations.AlterField(
            model_name='member',
            name='employee_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='员工号'),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='member',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', '男'), ('female', '女')], max_length=255, null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='member',
            name='type',
            field=models.IntegerField(blank=True, choices=[(0, '工人'), (1, '大组长'), (2, '经理'), (3, '总经理')], null=True, verbose_name='员工类别'),
        ),
        migrations.AlterField(
            model_name='team',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='小组号'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=255, verbose_name='小组名'),
        ),
        migrations.AlterField(
            model_name='teamgroupworkshop',
            name='group',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='level_relate', to='sms.Group', verbose_name='大组号'),
        ),
        migrations.AlterField(
            model_name='teamgroupworkshop',
            name='team',
            field=models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='level_relate', serialize=False, to='sms.Team', verbose_name='小组号'),
        ),
        migrations.AlterField(
            model_name='teamgroupworkshop',
            name='workshop',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='level_relate', to='sms.Workshop', verbose_name='车间号'),
        ),
        migrations.AlterField(
            model_name='teamstatmember',
            name='middle_shift_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='中班员工号'),
        ),
        migrations.AlterField(
            model_name='teamstatmember',
            name='morning_shift_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='早班员工号'),
        ),
        migrations.AlterField(
            model_name='teamstatmember',
            name='night_shift_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='晚班员工号'),
        ),
        migrations.AlterField(
            model_name='teamstatmember',
            name='stat_id',
            field=models.IntegerField(verbose_name='工位号'),
        ),
        migrations.AlterField(
            model_name='teamstatmember',
            name='team',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='team_stat_member', to='sms.Team', verbose_name='小组号'),
        ),
        migrations.AlterField(
            model_name='teamstatmember',
            name='update_time',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='记录时间'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='employee',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='employee_workshop', to='sms.Member', verbose_name='车间管理员工号'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='车间号'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='name',
            field=models.CharField(max_length=255, verbose_name='车间名'),
        ),
    ]
