# Generated by Django 2.2.7 on 2019-11-17 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_auto_20191116_1658'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': '大组信息', 'verbose_name_plural': '大组信息'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': '小组信息', 'verbose_name_plural': '小组信息'},
        ),
        migrations.AlterModelOptions(
            name='workshop',
            options={'verbose_name': '车间信息', 'verbose_name_plural': '车间信息'},
        ),
        migrations.CreateModel(
            name='Dpt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='sms.Member', verbose_name='生产部管理员工号')),
            ],
            options={
                'verbose_name': '生产部信息',
                'verbose_name_plural': '生产部信息',
                'db_table': 'sms_dpt_manager',
            },
        ),
    ]
