# Generated by Django 2.2.7 on 2019-11-20 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmsBaseInfo',
            fields=[
                ('alert_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='警报号')),
                ('stat_id', models.IntegerField(blank=True, null=True, verbose_name='工位号')),
                ('employee_id', models.IntegerField(blank=True, null=True, verbose_name='工位对应员工号')),
                ('employee_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='员工姓名')),
                ('reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='警报原因')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('final_deal_employee_id', models.IntegerField(blank=True, null=True, verbose_name='最终处理人员工号')),
                ('final_deal_employee_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='最终处理人姓名')),
                ('deal_role_id', models.IntegerField(blank=True, choices=[(1, '大组长'), (2, '经理'), (3, '总经理')], null=True, verbose_name='最终处理人角色类别')),
                ('status', models.IntegerField(blank=True, choices=[(1, '待处理'), (2, '已处理'), (3, '已关闭')], null=True, verbose_name='警报状态')),
            ],
            options={
                'verbose_name': '警报基本信息',
                'verbose_name_plural': '警报基本信息',
                'db_table': 'ams_base_info',
            },
        ),
        migrations.CreateModel(
            name='AmsConveyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_employee_id', models.IntegerField(blank=True, null=True, verbose_name='处理人员工号')),
                ('deal_employee_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='处理人姓名')),
                ('role_id', models.IntegerField(blank=True, choices=[(1, '大组长'), (2, '经理'), (3, '总经理')], null=True, verbose_name='处理人角色类别')),
                ('is_timeout', models.BooleanField(blank=True, default=False, null=True, verbose_name='是否超时')),
                ('is_delete', models.BooleanField(blank=True, default=False, null=True, verbose_name='是否删除')),
                ('time', models.DateTimeField(blank=True, null=True, verbose_name='收到警报的时间')),
                ('alert', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='alert_convey_info', to='ams.AmsBaseInfo', verbose_name='警报号')),
            ],
            options={
                'verbose_name': '警报传递信息',
                'verbose_name_plural': '警报传递信息',
                'db_table': 'ams_convey_info',
            },
        ),
    ]
