# Generated by Django 2.1.1 on 2019-11-23 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dmsworkerdaily',
            old_name='employee_id',
            new_name='worker_id',
        ),
        migrations.AlterIndexTogether(
            name='dmsworkerdaily',
            index_together={('worker_id', 'time')},
        ),
    ]
