# Generated by Django 2.2.7 on 2019-11-18 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cfgworkperiod',
            name='name',
            field=models.CharField(blank=True, choices=[('morning', '早'), ('middle', '中'), ('night', '晚')], max_length=255, null=True, verbose_name='时间段'),
        ),
    ]
