# Generated by Django 2.2.7 on 2019-11-16 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cfguserinquiry',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='配置开/关'),
        ),
    ]
