# Generated by Django 2.2.7 on 2019-11-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfg', '0002_auto_20191116_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cfgworkperiod',
            name='name',
            field=models.IntegerField(blank=True, choices=[(1, '早'), (2, '中'), (3, '晚')], null=True, verbose_name='时间段'),
        ),
        migrations.AlterField(
            model_name='cfgworkperiod',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='开始时间'),
        ),
    ]
