# Generated by Django 2.1.11 on 2019-12-03 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CfgAlertCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(verbose_name='低于标准效率的持续时间(单位:分钟)')),
                ('percent', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='低于标准效率的百分比(小数表示)')),
            ],
            options={
                'verbose_name': '警报条件参数',
                'verbose_name_plural': '警报条件参数',
                'db_table': 'cfg_alert_condition',
            },
        ),
        migrations.CreateModel(
            name='CfgAlertTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeout', models.IntegerField(verbose_name='超时传递时间(单位:分钟)')),
                ('max_timeout', models.IntegerField(verbose_name='警报最长处理时间(单位:分钟)')),
            ],
            options={
                'verbose_name': '警报传递参数',
                'verbose_name_plural': '警报传递参数',
                'db_table': 'cfg_alert_transfer',
            },
        ),
        migrations.CreateModel(
            name='CfgWorkPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('morning', '早'), ('middle', '中'), ('night', '晚')], max_length=255, null=True, verbose_name='时间段')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='结束时间')),
            ],
            options={
                'verbose_name': '工作时间段',
                'verbose_name_plural': '工作时间段',
                'db_table': 'cfg_work_period',
            },
        ),
    ]
